name: byyu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

# environment:
#   sdk: ">=2.7.0 <3.0.0"
# environment:
#   sdk: ">=3.0.6 <4.0.0"
environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4    
  fluttertoast: ^8.0.9
  intl: ^0.19.0
  shared_preferences: ^2.0.13
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  permission_handler: ^11.2.0
  image_picker: ^1.0.7
  image_cropper: ^4.0.1
  flutter_image_compress: ^2.1.0
  email_validator: ^2.0.1
  sms_autofill: ^2.3.1
  material_design_icons_flutter: ^7.0.7296
  geolocator: ^10.1.0
  geocoding: ^2.0.4
  cached_network_image: ^3.1.0+1
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.0.0
  dots_indicator: ^3.0.0
  flutter_local_notifications: ^17.0.1
  http: ^0.13.4
  path_provider: ^2.0.9
  google_maps_flutter: ^2.2.3
  flutter_rating_bar: ^4.0.0
  share_plus: ^7.2.1
  photo_view: ^0.14.0
  provider: ^6.1.1
  webview_flutter: ^2.0.4
  #geocoder: ^0.2.1
  geocoder2: ^1.4.0 # new one instead of geocoder we use geocoder2
  flutter_google_places: ^0.3.0
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  google_maps_webservice: ^0.0.19
  google_api_headers: ^1.5.0+1
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.3
  
#nikhil edits 
  
  google_nav_bar: ^5.0.6
  banner_image: ^1.0.7
  dropdown_textfield: ^1.0.8
  flutter_html: ^2.2.1
  flutter_holo_date_picker: ^1.1.2+1
  timeago: ^3.3.0
  material_text_fields: ^1.0.3
  google_sign_in: ^6.1.5
  country_picker: ^2.0.20
  
  #tap payment SDK acording to the document provided

  go_sell_sdk_flutter: ^2.4.6
  numberpicker: ^2.1.2
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^3.5.6
  # flutter_facebook_auth: ^7.0.0

  # facebook_app_events: ^0.19.2
  facebook_app_events: ^0.19.7
  go_router: ^13.0.1
  local_auth: ^2.1.6
  flutter_widget_from_html: ^0.9.0+1
  zoom_hover_pinch_image: ^1.0.3 
  html: ^0.15.4
  # flutter_captcha: ^1.0.0
  local_captcha: ^1.0.4
  
dependency_overrides:
  platform: ^3.1.0
  flutter_svg: ^1.0.3
  flutter_layout_grid: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.0.0
  

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/


  fonts:
    - family: metropolis_medium
      fonts:
        - asset: assets/fonts/metropolis_medium.otf
  
    - family: Adelia
      fonts:
        - asset: assets/fonts/Adelia.otf
          weight: 200
   
    - family: metropolis_regular
      fonts:
        - asset: assets/fonts/metropolis_regular.otf
          weight: 200
    - family: metropolis_semi_bold
      fonts:
        - asset: assets/fonts/metropolis_semi_bold.otf
          
    # 08-07 1st time the code to check push is successfull